### ISSUE TITLE
Unable to detect current script loaded via Data URI on iOS7

### ISSUE THREAD

**Issue by roman01la** [JamesMGreene/document.currentScript#1]
Looks like the code of the `_currentScript` getter runs all the way down to the [`getScriptUrlFromStack`](https://github.com/JamesMGreene/document.currentScript/blob/master/document.currentScript.js#L134), which can't parse Data URI src of the dynamically injected script. Notice that data uri encoded script can be with prefix `data:text/javascript;base64,` or with `data:text/javascript;charset=utf-8,` for IE.

**Comment by JamesMGreene** [comment]
FYI @roman01la: I revised this repo to be strictly spec-compliant. All of the other previously included behavior has been moved to [JamesMGreene/currentExecutingScript](https://github.com/JamesMGreene/currentExecutingScript).
