### ISSUE TITLE
Works with IE11

### ISSUE THREAD

**Issue by noopole** [JamesMGreene/document.currentScript#11]
Actually it's rather a non-issue since it seems to work fine with IE 11 now. Is the documentation out of date?

(I'm using version 1.0.7 from the 'currentExecutingScript' repository, though)

Thank you for this polyfill.

Bruno 

EDIT : 'currentScript' works but its 'ownerDocument' property is not the expected one (due to HTMLImports.js polyfill behaviour?)

**Comment by JamesMGreene** [comment]
The IE11 functional behavior you describe is now contained in [JamesMGreene/currentExecutingScript](https://github.com/JamesMGreene/currentExecutingScript), separate from this repo.

See [README.md#overview](https://github.com/JamesMGreene/document.currentScript#overview) for an explanation of why they are now separated.

**Comment by will-ob** [comment]
@JamesMGreene There's probably no chance support for 11 has magically appeared, is there? Do the sauce-labs tests just not fail for 11?

![saucelabs-img](https://cloud.githubusercontent.com/assets/1069495/15014908/b40c3800-11d6-11e6-9cd3-8b5cec40a6e7.jpg)

> Thank you for this polyfill

Seconded! :)

**Comment by will-ob** [comment]
Ah, wishful thinking. Testing on [microsoft's site](https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots) show polyfill still works as advertised and did not gain functionality overnight. I wonder why that test passes, though.

[This article](http://www.2ality.com/2014/05/current-script.html) looks like it might hold a workaround until IE11 dies. Is it possible they'll add this to 11 retroactively? Or is that totally unlikely?

**Comment by JamesMGreene** [comment]
> Do the sauce-labs tests just not fail for 11?

Correct, I wrote the unit tests such that this will detect if the polyfill can be performed or not.  If not, then it [uses `QUnit.skip` instead of `QUnit.test`](https://github.com/JamesMGreene/document.currentScript/blob/df158d37d0166c0ebe41462cc9b41e1260c233d8/test/tests.js#L56).

**Comment by JamesMGreene** [comment]
> [This article](http://www.2ality.com/2014/05/current-script.html) looks like it might hold a workaround until IE11 dies.

That article's suggestions will tend to work for many simple sites but leaves a lot of room for issues in sites with more complex script setups.  That said, I also created an alternative library that uses some of those techniques but with a slightly different intent (read the README here and there to get a better understanding of the differences): [JamesMGreene/currentExecutingScript](https://github.com/JamesMGreene/currentExecutingScript)

> Is it possible they'll add this to 11 retroactively? Or is that totally unlikely?

Highly unlikely that Microsoft will care enough to retroactively add this into IE11 since it has already been released for over 2.5 years. :cry:

**Comment by will-ob** [comment]
That all seems like solid reasoning. Thanks!
And for such a quick response ^_^
