### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by dominictarr** [JamesMGreene/document.currentScript#5]
you should publish this!

https://www.npmjs.org/currentscript is currently available!

**Comment by JamesMGreene** [comment]
FYI @dominictarr: I revised this repo to be strictly spec-compliant. All of the other previously included behavior has been moved to [JamesMGreene/currentExecutingScript](https://github.com/JamesMGreene/currentExecutingScript).

**Comment by dominictarr** [comment]
okay thanks
