### ISSUE TITLE
Should not return script element if operating asynchronously

### ISSUE THREAD

**Issue by JamesMGreene** [JamesMGreene/document.currentScript#7]
I found the caveat that is causing the cross-browser unit tests to fail when comparing results with the native browser implementation of `document.currentScript` on the [associated MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/document.currentScript):

> **Notes:**
> It's important to note that this will not reference the `<script>` element if the code in the script is being called as a callback or event handler; it will only reference the element while it's initially being processed.

The current behavior of this polyfill does **not** honor that behavior. Honestly, I find the behavior of this polyfill to actually be more useful... but it's hard to call it a "`document.currentScript` polyfill" if  it behaves differently in a arguably important manner.

I'm not even sure yet if the specified behavior is even _possible_ to achieve cross-browser for this polyfill.  However, if it is, then we should update the default behavior to operate as such but also add a `document._currentScript.strict = true/false` setting (defaulted to `true`) that would let you achieve the polyfill's current "loose" behavior of returning the script associated with an asynchronous callback.

**Comment by just-boris** [comment]
Of course I thought about this, and conclude that it is not possible to emulate native behaviour.
Take a look on [my testcases](https://github.com/just-boris/document.currentScript/blob/fix-consistency/test/tests.js#L12-48). Maybe it will be useful for you.

Also, all modern browsers support currentScript natively, except IE11, so maybe it should to work in IE, not phantomjs, which a little outdated in feature support

**Comment by JamesMGreene** [comment]
Thanks, I like your test approach. I'll definitely incorporate some of that, though I think I will also probably have to add some `iframe`-based tests for testing the rendering conditions (e.g. `defer` scripts, `async` scripts, etc.) as those operate slightly differently than dynamically added scripts. I should also add some tests for dynamically adding scripts to an earlier spot in the DOM (i.e. before some other existing `script` element).

**Comment by JamesMGreene** [comment]
Added another issue documenting some probe results from IE6 - IE11 and Opera 9 - 11 as a separate issue (#8), just to keep this issue not-so-bloated.

**Comment by JamesMGreene** [comment]
Attempted to make IE11 work using the `MutationObserver` API:
https://gist.github.com/JamesMGreene/d38bd9771ee87c10bee7/da47a1d15b23336d7aae93f6cdc3aa818a431c5f

That was a big failure due to MutationObserver's "performance enhancements" (i.e. batching). :-1:

I couldn't seem to get the old Mutation Events working in IE11 (e.g. `DOMSubtreeModified`) but I'll try again later....

**Comment by just-boris** [comment]
Mutation can't help there because it detects node attach. Script may load after attach.
I dived into [beforescriptexecute](https://developer.mozilla.org/en-US/docs/Web/Events/beforescriptexecute) event and so on, but it is has rare support in browsers as well

**Comment by JamesMGreene** [comment]
Yup, I already tried that too. :weary:

So frustrating that they removed `script.readyState`.... :-1:

**Comment by just-boris** [comment]
I thought we can try to wrap `document.createElement` as Polymer does it. https://github.com/webcomponents/webcomponentsjs/blob/master/src%2FShadowDOM%2Fwrappers%2FDocument.js#L55-72

**Comment by JamesMGreene** [comment]
Doesn't seem to buy us much, though, does it?

The only use case that seems to enable is preemptively modifying the contents of dynamically added inline scripts and/or proxying XHR requests for dynamically added same-origin or CORS-enabled external scripts (and then preemptively modiflying and `eval`-ing the contents). However, the latter case bastardizes the `script` element's integrity as it would require the `src` attribute to be not present, or _maybe_ to be specially proxied at the element level by setting up an "own" property descriptor with `Object.defineProperty`...?

**Comment by JamesMGreene** [comment]
The latter also messes with effective script origins. :confused:

**Comment by JamesMGreene** [comment]
I think I made this as "closed"/"resolved" as we can in commit b4b36269642786e6b22ef35288814ae09add8762. Also documented its limited scope of IE 6-10.

**Comment by JamesMGreene** [comment]
FYI @just-boris: I revised this repo to be strictly spec-compliant. All of the other previously included behavior has been moved to [JamesMGreene/currentExecutingScript](https://github.com/JamesMGreene/currentExecutingScript).
