### ISSUE TITLE
IE/Opera reliability results catalog

### ISSUE THREAD

**Issue by JamesMGreene** [JamesMGreene/document.currentScript#8]
# Test Page
http://cdn.rawgit.com/JamesMGreene/67d1e6c054699f24724c/raw/dafdd5f46eb04d2c2ba3cbe00f1e4209d492b642/index.html

### IE

**IE 6:** :+1:
![image](https://cloud.githubusercontent.com/assets/417751/5904580/37e9ea3c-a54f-11e4-9f98-5df99cdf5ea7.png)

**IE 7:** :+1:
![image](https://cloud.githubusercontent.com/assets/417751/5904602/6153b43e-a54f-11e4-8592-25c4260921e7.png)

**IE 8:** :+1:
![image](https://cloud.githubusercontent.com/assets/417751/5904587/47d52d26-a54f-11e4-9100-c07555ed1c8b.png)

**IE 9:** :+1:
![image](https://cloud.githubusercontent.com/assets/417751/5904222/9bb455c8-a54c-11e4-9764-de52469dcae8.png)

**IE 10:** :+1:
![image](https://cloud.githubusercontent.com/assets/417751/5904246/cb89f12c-a54c-11e4-8e64-178bddd366a4.png)

**IE 11:** :-1:
![image](https://cloud.githubusercontent.com/assets/417751/5904255/d60cbdd2-a54c-11e4-8d72-b14fac97ad97.png)

---

### Opera results

**Opera 9 (Mac):**  :-1: _(`script.readyState` present but has useless value of `"loaded"`)_
![image](https://cloud.githubusercontent.com/assets/417751/5903389/fafac9e6-a546-11e4-8920-edf3ce7f5c98.png)

**Opera 10 (Mac):**  :-1: _(`script.readyState` present but has useless value of `"loaded"`)_
![image](https://cloud.githubusercontent.com/assets/417751/5903432/462df000-a547-11e4-839f-7462b60bac88.png)

**Opera 11 (Mac):**  :-1:
![image](https://cloud.githubusercontent.com/assets/417751/5903498/9f0ebe98-a547-11e4-86a4-db2ce8bc9018.png)

---

### IE
**Result:** :+1: _(until IE11)_  

IE 6 - 10 are all _perfectly_ polyfill-able. IE11, however, is _**not**_.

Apparently IE has some weird bug where scripts still report a `readyState` of `"loading"` if they appended other script elements.

While using the IE6 VM on SauceLabs, it seemed like the browser was prone to crashing when a `script` element was dynamically added _after_ the page load had completed.

### Opera
**Result:** :-1:  

Initially, I thought that Opera (circa 9 - 12) would be as viable as oldIE for this polyfill because of the existence of `script.readyState` in oldOpera.  However, it turns out they removed that property in Opera 11, and that its value in Opera 9 - 10 was completely useless because it always only says `"loaded"`.

### Other Browsers
**Result:** :-1: _(unless already supporting native `document.currentScript`)_  

All other modern browsers basically look like the **IE11** result, with or without support for the native `document.currentScript` ("Native currentScript supported?"). :-1:

**Comment by JamesMGreene** [comment]
**Updated results for IE:** _(adding a script dynamically post-`load`)_
![image](https://cloud.githubusercontent.com/assets/417751/5905010/7d137436-a552-11e4-813a-414d03916e17.png)

**Updated test page:** http://cdn.rawgit.com/JamesMGreene/d38bd9771ee87c10bee7/raw/8cb30fcf39331099006599a91cee84fc4012aa83/index.html

**Comment by just-boris** [comment]
`readyState` has been removed since 11 version: https://msdn.microsoft.com/en-us/library/ie/ms534359(v=vs.85).aspx
And they don't have `currentScript` support in his plans

**Comment by JamesMGreene** [comment]
> `readyState` has been removed since 11 version: https://msdn.microsoft.com/en-us/library/ie/ms534359(v=vs.85).aspx

Yeah, I'm unfortunately aware of the former.  :cry:

> And they don't have `currentScript` support in their plans

Any confirmed source of information on that?

**Comment by just-boris** [comment]
There is no mention on progress board https://status.modern.ie/
Also, I left a suggestion on official uservoice: https://wpdev.uservoice.com/forums/257854-internet-explorer-platform/suggestions/6965085-support-document-currentscript-property 
And that is all as I can do

**Comment by JamesMGreene** [comment]
I'll see if I can throw any @jquery org weight behind it to at least ensure we don't miss `document.currentScript` in IE12+. :confused:

**Comment by JamesMGreene** [comment]
FYI @just-boris: I revised this repo to be strictly spec-compliant. All of the other previously included behavior has been moved to [JamesMGreene/currentExecutingScript](https://github.com/JamesMGreene/currentExecutingScript).
