### ISSUE TITLE
Latest version failing hard

### ISSUE THREAD

**Issue by ollym** [JamesMGreene/document.currentScript#9]
Thanks for this btw, I'm finding it really useful.

Having said that, I'm having to work off v0.1.7 as the v1.x releases are all broken.

Any reason behind this? Are you still maintaining this project?

**Comment by JamesMGreene** [comment]
Sorry to hear that. Can you explain what behavior you're seeing?

**Comment by ollym** [comment]
It's just not picking up the frame at all. I've had to resort to this:

```coffee
script = do ->

  # Desktop: Chrome 29+, FF 4+, Opera 16+, Safari 8+
  # Mobile: Android 4.4+, Chrome, FF, iOS 8+
  return document.currentScript if 'currentScript' of document

  # Desktop: IE 6-10
  if supports_script_ready_state
    for script in scripts
      return script if script.readyState is 'interactive'

  async = do ->
    for script in scripts
      return false if script.async
    return true

  # If no scripts before are async, pick the last one
  return scripts[scripts.length - 1] unless async
```

**Comment by JamesMGreene** [comment]
That's kind of what I figured.  So here's the deal....

In `v1.0.0`, I extracted all of the non-spec-compliant functionality and rebuilt that as a separate module/library: https://github.com/JamesMGreene/currentExecutingScript/

See [README.md#overview](https://github.com/JamesMGreene/document.currentScript/blob/master/README.md#overview) for more info.

**Comment by ollym** [comment]
@JamesMGreene Right. But it has no code?

**Comment by JamesMGreene** [comment]
D'oh... forgot to `push`! Check again now. :blushing:

**Comment by JamesMGreene** [comment]
P.S. Any help and/or suggestions would be very much welcomed for currenntExecutingScript!

**Comment by ollym** [comment]
@JamesMGreene It would be helpful if you could list the techniques you're using for script detection in english. The source code structure makes it difficult to see them without properly reading through the code.

**Comment by JamesMGreene** [comment]
@ollym Do you mean for this repo, or for the currentExecutingScript repo (or both)?

**Comment by ollym** [comment]
@JamesMGreene currentExecutingScript

**Comment by JamesMGreene** [comment]
OK, that's what I figured. Issue created to track this: JamesMGreene/currentExecutingScript#6
